sequenceDiagram
    participant browser
    participant server

    browser->>browser: User writes in the text field
    browser->>browser: User clicks the Save button

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/notes
    Note right of server: Request body contains the new note's content

    activate server
    server-->>browser: Confirmation of the new note creation (e.g., status code 201)
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/notes.html
    activate server
    server-->>browser: Notes document in html
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    activate server
    server-->>browser: Main styles in css
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.js
    activate server
    server-->>browser: Main file in js
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate server
    server-->>browser: JSON data (updated)
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate server
    server-->>browser: JSON data (updated)
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/favicon.ico
    activate server
    server-->>browser: Small icon image
    deactivate server

    Note right of browser: Browser executes the callback to render the updated list of notes
