### Delete person with id 2
DELETE http://localhost:3001/api/persons/2

### Delete person with id 1
DELETE http://localhost:3001/api/persons/1

### Get all persons (to verify deletion)
GET http://localhost:3001/api/persons

### Add a new person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "John Doe",
  "number": "555-1234"
}

### Add another person 
POST https://phonebook-backend-wwpx.onrender.com/api/persons
Content-Type: application/json

{
  "name": "Filip G",
  "number": "123-456-789"
}